Create String.h
Skroler/MIPT-Course-1 pull request #11
Opened 2020-12-22 18:07 UTC by Skroler

https://contest.yandex.ru/contest/21872/run-report/45793604/

2020-12-22 21:21 UTC, DmitryKorepanov requested changes

2020-12-22 21:21 UTC, DmitryKorepanov commented on String.h
> +                    ans = this->substr(i, s.sz);
это очень дорогой способ проверки. надо использовать буфер и не порождать доп строк

2020-12-22 21:21 UTC, DmitryKorepanov commented on String.h
> +            *this += s.str[i];
тоже не оптимально, если в короткой строке прибавить длинную

2020-12-22 21:21 UTC, DmitryKorepanov commented on String.h
> +        String ans;
тоже никаких объектов создаваться не должно

2020-12-24 22:17 UTC, Skroler commented on String.h
> +                    ans = this->substr(i, s.sz);
Исправил

2020-12-24 22:17 UTC, Skroler commented on String.h
> +        String ans;
Исправил

2020-12-24 22:39 UTC, Skroler commented on String.h
> +            *this += s.str[i];
Исправил

2020-12-25 11:43 UTC, DmitryKorepanov approved these changes

2021-03-29 08:21 UTC, merged