Create Program D
Skroler/MIPT-Course-1 pull request #2
Opened 2020-10-24 10:51 UTC by Skroler

2020-10-24 23:18 UTC, DmitryKorepanov requested changes

2020-10-24 23:18 UTC, DmitryKorepanov commented on Program D
> +    std::deque <int> Goblins_1 = std::deque<int>();
Надо сделать класс очередь, который будет уметь вставлять в начало в средину.

2020-10-27 19:04 UTC, Skroler commented on Program D
> +    std::deque <int> Goblins_1 = std::deque<int>();
Данный класс реализовал.

2020-10-31 19:09 UTC, DmitryKorepanov approved these changes

2020-11-02 17:10 UTC, merged