Task d
Skroler/MIPT-Course-1 pull request #5
Opened 2020-10-27 20:33 UTC by Skroler

96798404

2020-11-01 22:30 UTC, DmitryKorepanov requested changes

2020-11-01 22:30 UTC, DmitryKorepanov commented on D.cpp
> +    Item getMin();
Item не должно быть в публичных методах класса

2020-11-01 22:30 UTC, DmitryKorepanov commented on D.cpp
> +Heap::Heap(int _max_size) : data (new Item[_max_size + 1]), n (0), max_size (_max_size) {}
max_size плохая константа, куча должна уметь динамически расти

2020-11-15 22:00 UTC, Skroler commented on D.cpp
> +Heap::Heap(int _max_size) : data (new Item[_max_size + 1]), n (0), max_size (_max_size) {}
Ошибку исправил

2020-11-18 00:20 UTC, DmitryKorepanov approved these changes

2020-12-16 17:59 UTC, merged