Prog_4a
Skroler/MIPT-Course-1 pull request #8
Opened 2020-12-17 21:01 UTC by Skroler

задача 4а
https://codeforces.com/group/R3IJoiTue4/contest/301990/submission/99635606

2020-12-19 17:19 UTC, DmitryKorepanov requested changes

2020-12-19 17:19 UTC, DmitryKorepanov commented on Con4_A
> +    while (root != nullptr) {
удалять надо за О(n)

2020-12-19 17:19 UTC, DmitryKorepanov commented on Con4_A
> +            Node* right_1 = delmin(node_1->right);
удаление должно выполняться за один проход по дереву, для этого надо реализовать метод findAndDelMin

2020-12-19 17:19 UTC, DmitryKorepanov commented on Con4_A
> +    int min = 2000000000;
вымышленных констант быть не должно, метод должен явно возвращать признак, что такого значения нет

2020-12-20 01:44 UTC, Skroler commented on Con4_A
> +    int min = 2000000000;
Исправлено

2020-12-20 01:59 UTC, Skroler commented on Con4_A
> +            Node* right_1 = delmin(node_1->right);
исправил

2020-12-20 02:00 UTC, Skroler commented on Con4_A
> +    while (root != nullptr) {
Исправлено

2020-12-20 03:33 UTC, Skroler commented on Con4_A
> +            Node* right_1 = delmin(node_1->right);
исправлено

2020-12-20 10:05 UTC, DmitryKorepanov requested changes

2020-12-20 10:05 UTC, DmitryKorepanov commented on Con4_A
> +    if (a == key) std::cout << "none" << "\n";
ввод вывод должен быть только в main

2020-12-20 10:05 UTC, DmitryKorepanov commented on Con4_A
> +void AVL::Exists(int key) {
ввод вывод только в main

2020-12-20 10:05 UTC, DmitryKorepanov commented on Con4_A
> +            ans->right = delmin(node_1->right);
не исправлено!

2020-12-20 11:30 UTC, Skroler commented on Con4_A
> +void AVL::Exists(int key) {
Исправлено

2020-12-20 11:35 UTC, Skroler commented on Con4_A
> +    if (a == key) std::cout << "none" << "\n";
исправлено

2021-03-29 08:21 UTC, merged